steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/staj-gemkom/cloud-run-source-deploy/gemkom-tracker:latest', '.']
images:
  - 'europe-west1-docker.pkg.dev/staj-gemkom/cloud-run-source-deploy/gemkom-tracker:latest'
